### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by fvieir** [Leandrolsantos/formulario-de-triagem-virtual-para-pronto-socorro#1]
Fala Lenadro.

Conforme deixado o Feedback e orientações no Discord, segue minhas solicitação para atualizar readme.

Qualquer duvida é so chamar.

Forte abraço

**Comment by Leandrolsantos** [comment]
Já dei uma atualizada no README e deixei o repositório mais organizado para quem ver o projeto, mais uma vez obrigado pelas dicas.
