### ISSUE TITLE
Estrutura de pasta e Deploy

### ISSUE THREAD

**Issue by fvieir** [Leandrolsantos/formulario-de-triagem-virtual-para-pronto-socorro#2]
Olá Leandro.

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para estrtutura das pastas e deploy.

Segue uma ideia de como estruturar as pastas.

![image](https://user-images.githubusercontent.com/65264206/196414235-35e7d046-da1a-42d8-8206-bbc0b86641af.png)

Qualquer duvida é so chamar.

**Comment by Leandrolsantos** [comment]
Obrigado, em breve irei atualizar o projeto com os arquivos organizados.
